# Compute the true site pattern probs to use in getting the likelihood -- symmetric case

# The site pattern probabilities are ordered as follows:
# xxxx
# xxxy
# xyxx
# xyxy
# xxyy
# xxyz
# yzxx
# xyzx
# xyzw

GetTrueProbsSymm = function(myt1,myt2,myt3,theta,alpha) {

      #these get us the site pattern frequencies that match the data sets generated by the seq-gen pipeline
      t1 = myt1*theta  # t1*theta
      t2 = myt2*theta  # t2*theta
      t3 = myt3*theta  # t3*theta
      t = 2*theta      # 2*theta
      m = alpha        # mu for JC69

      #compute the C matrix
      cmat = matrix(0,ncol=9,nrow=9)
      # row 1
      for (i in 1:9) cmat[1,i] = 1/256
      # row 2
      cmat[2,1]=cmat[2,3]=cmat[2,5]=cmat[2,7] = 3/(256*(1+m*t))
      cmat[2,2]=cmat[2,4]=cmat[2,6]=cmat[2,8]=cmat[2,9]=-1/(256*(1+m*t))
      # row 3
      cmat[3,1]=cmat[3,2]=cmat[3,5]=cmat[3,6]=3/(256*(1+m*t))
      cmat[3,3]=cmat[3,4]=cmat[3,7]=cmat[3,8]=cmat[3,9]=-1/(256*(1+m*t))
      # row 4
      cmat[4,1]=cmat[4,5] = 9/(256*(1+m*t)^2)
      cmat[4,2]=cmat[4,3]=cmat[4,6]=cmat[4,7] = -3/(256*(1+m*t)^2)
      cmat[4,4]=cmat[4,8]=cmat[4,9] = 1/(256*(1+m*t)^2)
      # row 5
      cmat[5,1]=12/(256*(1+m*t))
      cmat[5,2]=cmat[5,3]=cmat[5,4]=4/(256*(1+m*t))
      cmat[5,5]=cmat[5,6]=cmat[5,7]=cmat[5,9]=-4/(256*(1+m*t))
      cmat[5,8]=0
      # row 6
      cmat[6,1]=24/(256*(1+m*t)*(2+m*t))
      cmat[6,2]=cmat[6,4]=cmat[6,5]=cmat[6,7]=-8/(256*(1+m*t)*(2+m*t))
      cmat[6,3]=8/(256*(1+m*t)*(2+m*t))
      cmat[6,6]=cmat[6,9]=8/(256*(1+m*t)*(2+m*t))
      cmat[6,8]=0
      # row 7
      cmat[7,1]=24/(256*(1+m*t)*(2+m*t))
      cmat[7,2]=8/(256*(1+m*t)*(2+m*t))
      cmat[7,3]=cmat[7,4]=cmat[7,5]=cmat[7,6]=-8/(256*(1+m*t)*(2+m*t))
      cmat[7,7]=cmat[7,9]=8/(256*(1+m*t)*(2+m*t))
      cmat[7,8]=0
      # row 8
      cmat[8,1]=48/(256*(1+m*t)*(2+m*t)^2)
      cmat[8,2]=cmat[8,3]=cmat[8,5]=-16/(256*(1+m*t)*(2+m*t)^2)
      cmat[8,4]=cmat[8,6]=cmat[8,7]=16/(256*(1+m*t)*(2+m*t)^2)
      cmat[8,8]=0
      cmat[8,9]=-16/(256*(1+m*t)*(2+m*t)^2)
      # row 9
      cmat[9,1]=6*m*t*(4+m*t)*(4+3*m*t)/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,2]=cmat[9,3]=-2*m*t*(4+m*t)*(4+3*m*t)/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,4]=m*t*(32+40*m*t+10*(m^2)*(t^2))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,5]=2*m*t*(4+m*t)^2/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,6]=cmat[9,7]=2*(m^2)*(t^2)*(4+m*t)/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,8]=-(m^2)*(t^2)*(4+2*m*t)/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
      cmat[9,9]=2*(m^3)*(t^3)/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))

      #get the beta vector
      beta = matrix(0,ncol=1,nrow=9)
      beta[1,1]=1
      beta[2,1]=exp(-2*m*t1)
      beta[3,1]=exp(-2*m*t2)
      beta[4,1]=exp(-2*m*t1)*exp(-2*m*t2)
      beta[5,1]=exp(-2*m*t3)
      beta[6,1]=exp(-m*t1)*exp(-2*m*t3)
      beta[7,1]=exp(-m*t2)*exp(-2*m*t3)
      beta[8,1]=exp(-m*t1)*exp(-m*t2)*exp(-2*m*t3)
      beta[9,1]=exp(2*t1/t)*exp(2*t2/t)*exp(-4*t3*(m+1/t))

      weights=matrix(0,ncol=9,nrow=1)
      w1=weights[1,1]=4
      w2=weights[1,2]=24
      w3=weights[1,3]=24
      w4=weights[1,4]=24
      w5=weights[1,5]=12
      w6=weights[1,6]=24
      w7=weights[1,7]=24
      w8=weights[1,8]=24*4
      w9=weights[1,9]=24

      p=t(cmat)%*%beta
      # check that we have counted all site pattern probabilities
      #sum(weights)
      # check that we have a valid probability distribution
      #print(weights%*%p)
      #sum(p)

      #print(p)

      return(p)
  }


# Now define the function to compute the likelihood for a given choice of parameters
# define x = c(myt1,myt2,myt3,theta)

GetLikSymm = function(x){

      myprobs = GetTrueProbsSymm(x[1],x[2],x[3],x[4],4.0/3.0)
      if (sum(myprobs>0)==9 && sum(x>0)==4 && sum(x<5)==4 && x[3]>x[1] && x[3]>x[2]) {
      
      loglik = n1*log(4*myprobs[1,1]) + n2*log(24*myprobs[2,1]) + n3*log(24*myprobs[3,1]) + n4*log(24*myprobs[4,1]) + n5*log(12*myprobs[5,1]) + n6*log(24*myprobs[6,1]) + n7*log(24*myprobs[7,1]) + n8*log(96*myprobs[8,1]) + n9*log(24*myprobs[9,1])

      return(-1.0*loglik)
    } else return(9999999999.0);

  }


# Compute the true site pattern probs to use in getting the likelihood -- asymmetric case

# The site pattern probabilities are ordered as follows:
# xxxx   
# xxxy
# xyxx
# yxxx
# xxyy
# xyxy
# xxyz
# yzxx
# xyxz
# yxxz
# xyzw


GetTrueProbsAsymm = function(myt1,myt2,myt3,theta,alpha) {

    #these get us the site pattert frequetcies that match the data sets geterated by the seq-get pipelite
    t1 = myt1*theta  # t1*theta
    t2 = myt2*theta  # t2*theta
    t3 = myt3*theta  # t3*theta
    t = 2*theta      # 2*theta
    m = alpha        # mu for JC69

    #compute the C matrix
    cmat = matrix(0,ncol=10,nrow=11)
    # row 1
    cmat[1,1] = 1/256
    cmat[1,2] = 3/((256)*(1+m*t))
    cmat[1,3] = 6/(256*(1+m*t))
    cmat[1,4] = 12/(256*(1+m*t)*(2+m*t))
    cmat[1,5] = 9/(256*(1+m*t))
    cmat[1,6] = 12/(256*(1+m*t)*(2+m*t))
    cmat[1,7] = 9/(256*(1+m*t)^2)
    cmat[1,8] = 24/(256*(1+m*t)*(2+m*t))
    cmat[1,9] = 48/(256*(1+m*t)*(2+m*t)^2)
    cmat[1,10] = (6*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 2
    cmat[2,1] = 1/256
    cmat[2,2] = -1/(256*(1+m*t))
    cmat[2,3] = 2/(256*(1+m*t))
    cmat[2,4] = -4/(256*(1+m*t)*(2+m*t))
    cmat[2,5] = 5/(256*(1+m*t))
    cmat[2,6] = -4/(256*(1+m*t)*(2+m*t))
    cmat[2,7] = -3/(256*(1+m*t)^2)
    cmat[2,8] = 8/(256*(1+m*t)*(2+m*t))
    cmat[2,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[2,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 3
    cmat[3,1] = 1/256
    cmat[3,2] = 3/(256*(1+m*t))
    cmat[3,3] = -2/(256*(1+m*t))
    cmat[3,4] = -4/(256*(1+m*t)*(2+m*t))
    cmat[3,5] = 5/(256*(1+m*t))
    cmat[3,6] = 12/(256*(1+m*t)*(2+m*t))
    cmat[3,7] = -3/(256*(1+m*t)^2)
    cmat[3,8] = -8/(256*(1+m*t)*(2+m*t))
    cmat[3,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[3,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 4
    cmat[4,1] = 1/256
    cmat[4,2] = 3/(256*(1+m*t))
    cmat[4,3] = 6/(256*(1+m*t))
    cmat[4,4] = 12/(256*(1+m*t)*(2+m*t))
    cmat[4,5] = -3/(256*(1+m*t))
    cmat[4,6] = -4/(256*(1+m*t)*(2+m*t))
    cmat[4,7] = -3/(256*(1+m*t)^2)
    cmat[4,8] = -8/(256*(1+m*t)*(2+m*t))
    cmat[4,9] = -16/(256*(1+m*t)*(2+m*t)^2)
    cmat[4,10] = -(2*m*t*(4+m*t)*(4+3*m*t))/(256*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    #row 5
    cmat[5,1] = 1/256
    cmat[5,2] = 3/((256)*(1+m*t))
    cmat[5,3] = -2/((256)*(1+m*t))
    cmat[5,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[5,5] = 1/((256)*(1+m*t))
    cmat[5,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[5,7] = 9/((256)*(1+m*t)^2)
    cmat[5,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[5,9] = -16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[5,10] = (2*m*t*(4+m*t)^2)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 6
    cmat[6,1] = 1/256
    cmat[6,2] = -1/((256)*(1+m*t))
    cmat[6,3] = 2/((256)*(1+m*t))
    cmat[6,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[6,5] = 1/((256)*(1+m*t))
    cmat[6,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[6,7] = 1/((256)*(1+m*t)^2)
    cmat[6,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[6,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[6,10] = m*t*(2*16+40*m*t+(10)*(m^2)*(t^2))/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 7
    cmat[7,1] = 1/256
    cmat[7,2] = -1/((256)*(1+m*t))
    cmat[7,3] = -2/((256)*(1+m*t))
    cmat[7,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[7,5] = 1/((256)*(1+m*t))
    cmat[7,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[7,7] = -3/((256)*(1+m*t)^2)
    cmat[7,8] = -8/((256)*(1+m*t)*(2+m*t))
    cmat[7,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[7,10] = 2*(m^2)*(t^2)*(4+m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 8
    cmat[8,1] = 1/256
    cmat[8,2] = 3/((256)*(1+m*t))
    cmat[8,3] = -2/((256)*(1+m*t))
    cmat[8,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[8,5] = -3/((256)*(1+m*t))
    cmat[8,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[8,7] = -3/((256)*(1+m*t)^2)
    cmat[8,8] = 8/((256)*(1+m*t)*(2+m*t))
    cmat[8,9] = 16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[8,10] = 2*(m^2)*(t^2)*(4+m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 9
    cmat[9,1] = 1/256
    cmat[9,2] = -1/((256)*(1+m*t))
    cmat[9,3] = -2/((256)*(1+m*t))
    cmat[9,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[9,5] = 1/((256)*(1+m*t))
    cmat[9,6] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[9,7] = 1/((256)*(1+m*t)^2)
    cmat[9,8] = 0
    cmat[9,9] = 0
    cmat[9,10] = -(m^2)*(t^2)*(4+2*m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 10
    cmat[10,1] = 1/256
    cmat[10,2] = -1/((256)*(1+m*t))
    cmat[10,3] = 2/((256)*(1+m*t))
    cmat[10,4] = -4/((256)*(1+m*t)*(2+m*t))
    cmat[10,5] = -3/((256)*(1+m*t))
    cmat[10,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[10,7] = 1/((256)*(1+m*t)^2)
    cmat[10,8] = 0
    cmat[10,9] = 0
    cmat[10,10] = -(m^2)*(t^2)*(4+2*m*t)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))
    # row 11
    cmat[11,1] = 1/256
    cmat[11,2] = -1/((256)*(1+m*t))
    cmat[11,3] = -2/((256)*(1+m*t))
    cmat[11,4] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[11,5] = -3/((256)*(1+m*t))
    cmat[11,6] = 4/((256)*(1+m*t)*(2+m*t))
    cmat[11,7] = 1/((256)*(1+m*t)^2)
    cmat[11,8] = 8/((256)*(1+m*t)*(2+m*t))
    cmat[11,9] = -16/((256)*(1+m*t)*(2+m*t)^2)
    cmat[11,10] = 2*(m^3)*(t^3)/((256)*((1+m*t)^2)*((2+m*t)^2)*(3+m*t))

    # get the beta vector
    beta = matrix(0,ncol=1,nrow=10)
    beta[1,1]=1
    beta[2,1]=exp(-2*m*t1)
    beta[3,1]=exp(-2*m*t2)
    beta[4,1]=exp(-m*t1)*exp(-2*m*t2)
    beta[5,1]=exp(-2*m*t3)
    beta[6,1]=exp(-m*t1)*exp(-2*m*t3)
    beta[7,1]=exp(-2*m*t1)*exp(-2*m*t3)
    beta[8,1]=exp(-m*t2)*exp(-2*m*t3)
    beta[9,1]=exp(-m*t1)*exp(-m*t2)*exp(-2*m*t3)
    beta[10,1]=exp((2/t)*(t1-t2))*exp(-2*m*(t2+t3))

    weights=matrix(0,ncol=11,nrow=1)
    w1=weights[1,1]=4
    w2=weights[1,2]=24
    w3=weights[1,3]=12
    w4=weights[1,4]=12
    w5=weights[1,5]=12
    w6=weights[1,6]=24
    w7=weights[1,7]=24
    w8=weights[1,8]=24
    w9=weights[1,9]=48
    w10=weights[1,10]=48
    w11=weights[1,11]=24

    p=cmat%*%beta
    # check that we have counted all site pattern probabilities
    #sum(weights)
    # check that we have a valid probability distribution
    #p=t(cmat)%*%beta
    #print(weights%*%p)
     
    return(p)
  }


# Now define the function to compute the likelihood for a given choice of parameters
# define x = c(myt1,myt2,myt3,theta)

GetLikAsymm = function(x){

   myprobs = GetTrueProbsAsymm(x[1],x[2],x[3],x[4],4.0/3.0)

    if (sum(myprobs>0)==11 && sum(x>0)==4 && sum(x<5)==4 && x[2]>x[1] && x[3]>x[2]) {
   
      loglik = n1*log(4*myprobs[1,1]) + n2*log(24*myprobs[2,1]) + n3*log(12*myprobs[3,1]) + n4*log(12*myprobs[4,1]) + n5*log(12*myprobs[5,1]) + n6*log(24*myprobs[6,1]) + n7*log(24*myprobs[7,1]) + n8*log(24*myprobs[8,1]) + n9*log(48*myprobs[9,1]) + n10*log(48*myprobs[10,1]) + n11*log(24*myprobs[11,1])

      return(-1.0*loglik)
    } else return(9999999999.0);
 }


#y = c(1.0,1.5,2.0,0.2/2)
#optim(y,GetLikSymm)
